const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Movie = require("./models/Movie");

dotenv.config();

const seedMovies = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB Connected");

    const movies = [
      {
        title: "Interstellar",
        description: "A team travels through a wormhole in space.",
        type: "movie",
        language: "English",
        posterUrl: "",
        cast: ["Matthew McConaughey", "Anne Hathaway"],
        length: 200,
        genre: ["Sci-Fi", "Adventure"],
        releaseDate: new Date("2014-11-07"),
      },
      {
        title: "Breaking Bad",
        description: "A chemistry teacher turns into a drug lord.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Bryan Cranston", "Aaron Paul"],
        length: 80,
        genre: ["Crime", "Drama"],
        releaseDate: new Date("2008-01-20"),
      },
      {
        title: "The Office",
        description: "Mockumentary about office workers.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Steve Carell", "Rainn Wilson"],
        length: 80,
        genre: ["Comedy"],
        releaseDate: new Date("2005-03-24"),
      },
      {
        title: "Attack on Titan",
        description: "Humans fight titans in a walled city.",
        type: "series",
        language: "Japanese",
        posterUrl: "",
        cast: ["Yuki Kaji", "Marina Inoue"],
        length: 180,
        genre: ["Anime", "Action"],
        releaseDate: new Date("2013-04-07"),
      },
      {
        title: "Inception",
        description: "A thief enters dreams to steal secrets.",
        type: "movie",
        language: "English",
        posterUrl: "",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
        length: 80,
        genre: ["Sci-Fi", "Action"],
        releaseDate: new Date("2010-07-16"),
      },
      {
        title: "La Casa de Papel",
        description: "A group of robbers plan a heist on the Royal Mint.",
        type: "series",
        language: "Spanish",
        posterUrl: "",
        cast: ["Álvaro Morte", "Úrsula Corberó"],
        length: 80,
        genre: ["Action", "Thriller"],
        releaseDate: new Date("2017-05-02"),
      },
      {
        title: "Parasite",
        description: "A poor family schemes to become employed by a wealthy family.",
        type: "movie",
        language: "Korean",
        posterUrl: "",
        cast: ["Song Kang-ho", "Lee Sun-kyun"],
        length: 130,
        genre: ["Drama", "Thriller"],
        releaseDate: new Date("2019-05-30"),
      },
      {
        title: "Game of Thrones",
        description: "Noble families vie for control of the Iron Throne.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Emilia Clarke", "Kit Harington"],
        length: 80,
        genre: ["Fantasy", "Drama"],
        releaseDate: new Date("2011-04-17"),
      },
      {
        title: "Spirited Away",
        description: "A young girl becomes trapped in a mysterious spirit world.",
        type: "movie",
        language: "Japanese",
        posterUrl: "",
        cast: ["Rumi Hiiragi", "Miyu Irino"],
        length: 80,
        genre: ["Animation", "Fantasy"],
        releaseDate: new Date("2001-07-20"),
      },
      {
        title: "The Crown",
        description: "A historical drama about the reign of Queen Elizabeth II.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Claire Foy", "Olivia Colman"],
        length: 80,
        genre: ["Biography", "Drama"],
        releaseDate: new Date("2016-11-04"),
      },
      {
        title: "The Godfather",
        description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        type: "movie",
        language: "English",
        posterUrl: "",
        cast: ["Marlon Brando", "Al Pacino"],
        length: 80,
        genre: ["Crime", "Drama"],
        releaseDate: new Date("1972-03-24"),
      },
      {
        title: "The Dark Knight",
        description: "Batman faces the Joker, a criminal mastermind.",
        type: "movie",
        language: "English",
        posterUrl: "",
        cast: ["Christian Bale", "Heath Ledger"],
        length: 80,
        genre: ["Action", "Crime"],
        releaseDate: new Date("2008-07-18"),
      },
      {
        title: "Stranger Things",
        description: "A group of kids uncover supernatural mysteries in their town.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Winona Ryder", "David Harbour"],
        length: 80,
        genre: ["Drama", "Fantasy"],
        releaseDate: new Date("2016-07-15"),
      },
      {
        title: "The Matrix",
        description: "A computer hacker learns about the true nature of reality.",
        type: "movie",
        language: "English",
        posterUrl: "",
        cast: ["Keanu Reeves", "Laurence Fishburne"],
        length: 80,
        genre: ["Action", "Sci-Fi"],
        releaseDate: new Date("1999-03-31"),
      },
      {
        title: "Sherlock",
        description: "A modern update to the classic detective stories.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Benedict Cumberbatch", "Martin Freeman"],
        length: 12,
        genre: ["Crime", "Drama"],
        releaseDate: new Date("2010-07-25"),
      },
      {
        title: "The Shawshank Redemption",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        type: "movie",
        language: "English",
        posterUrl: "",
        cast: ["Tim Robbins", "Morgan Freeman"],
        length: 80,
        genre: ["Drama"],
        releaseDate: new Date("1994-09-23"),
      },
      {
        title: "Black Mirror",
        description: "An anthology series exploring a twisted, high-tech multiverse.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Daniel Kaluuya", "Jessica Brown Findlay"],
        length: 80,
        genre: ["Drama", "Sci-Fi"],
        releaseDate: new Date("2011-12-04"),
      },
      {
        title: "The Simpsons",
        description: "An animated sitcom about the Simpson family.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Dan Castellaneta", "Julie Kavner"],
        length: 80,
        genre: ["Animation", "Comedy"],
        releaseDate: new Date("1989-12-17"),
      },
      {
        title: "The Witcher",
        description: "A monster hunter battles dark forces in a medieval world.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Henry Cavill", "Anya Chalotra"],
        length: 80,
        genre: ["Action", "Adventure", "Fantasy"],
        releaseDate: new Date("2019-12-20"),
      },
      {
        title: "Narcos",
        description: "The true story of Colombia's infamously violent and powerful drug cartels.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Wagner Moura", "Pedro Pascal"],
        length: 80,
        genre: ["Crime", "Drama"],
        releaseDate: new Date("2015-08-28"),
      },
      {
        title: "The Mandalorian",
        description: "A lone bounty hunter in the outer reaches of the galaxy.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Pedro Pascal", "Gina Carano"],
        length: 80,
        genre: ["Action", "Adventure", "Fantasy"],
        releaseDate: new Date("2019-11-12"),
      },
      {
        title: "Chernobyl",
        description: "A dramatization of the 1986 Chernobyl nuclear disaster.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Jared Harris", "Stellan Skarsgård"],
        length: 80,
        genre: ["Drama", "History"],
        releaseDate: new Date("2019-05-06"),
      },
      {
        title: "The Boys",
        description: "A group of vigilantes set out to take down corrupt superheroes.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Karl Urban", "Jack Quaid"],
        length: 80,
        genre: ["Action", "Comedy", "Drama"],
        releaseDate: new Date("2019-07-26"),
      },
      {
        title: "Better Call Saul",
        description: "A prequel to Breaking Bad, focusing on the character of Saul Goodman.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Bob Odenkirk", "Jonathan Banks"],
        length: 80,
        genre: ["Crime", "Drama"],
        releaseDate: new Date("2015-02-08"),
      },
      {
        title: "The Marvelous Mrs. Maisel",
        description: "A housewife in the 1950s pursues a career in stand-up comedy.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Rachel Brosnahan", "Tony Shalhoub"],
        length: 80,
        genre: ["Comedy", "Drama"],
        releaseDate: new Date("2017-03-17"),
      },
      {
        title: "Fargo",
        description: "An anthology series inspired by the Coen brothers' film of the same name.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Billy Bob Thornton", "Martin Freeman"],
        length: 80,
        genre: ["Crime", "Drama", "Thriller"],
        releaseDate: new Date("2014-04-15"),
      },
      {
        title: "The Handmaid's Tale",
        description: "A dystopian future where a totalitarian regime has taken control of the United States.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Elisabeth Moss", "Yvonne Strahovski"],
        length: 80,
        genre: ["Drama", "Sci-Fi", "Thriller"],
        releaseDate: new Date("2017-04-26"),
      },
      {
        title: "Prison Break",
        description: "A man is wrongly convicted of a crime and devises a plan to escape from prison.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["Wentworth Miller", "Dominic Purcell"],
        length: 80,
        genre: ["Action", "Crime", "Drama"],
        releaseDate: new Date("2005-08-29"),
      },
      {
        title: "The Sopranos",
        description: "A mob boss tries to balance the demands of his crime family with those of his personal life.",
        type: "series",
        language: "English",
        posterUrl: "",
        cast: ["James Gandolfini", "Edie Falco"],
        length: 80,
        genre: ["Crime", "Drama"],
        releaseDate: new Date("1999-01-10"),
      }
    ];

    await Movie.insertMany(movies);

    console.log("Movies added successfully ✅");
    process.exit();
  } catch (err) {
    console.error("❌ Failed to seed movies:", err);
    process.exit(1);
  }
};

seedMovies();
